'use strict';

const SPEEDRUN_VERSION=1;
const SPEEDRUN_STEP=1/60;
const SPEEDRUN_KEEP=new Set(['resume','speedrunRecords','music','sfx','musicVolume','sfxVolume','motion','touch','quality','textSpeed','dialogueVoice']);
const SPEEDRUN_DEFAULT_FORMS={primary:'emberBolt',flare:'crownFlare',dash:'cinderstep'};
const SPEEDRUN_GUARDIANS=[
 {floor:5,name:'STAR WARDEN'},{floor:10,name:'HOLLOW MATRIARCH'},{floor:15,name:'BELLKEEPER'},{floor:20,name:'EMBER COLOSSUS'},{floor:25,name:'GLASS ASTRONOMER'},
 {floor:30,name:'PALE SCRIBE'},{floor:35,name:'TWIN REGENTS'},{floor:40,name:'VOID SERAPH'},{floor:45,name:'OBSIDIAN TYRANT'},{floor:50,name:'FIRST KEEPER'}
];
const speedNativeRandom=Math.random;
let speedPending=null,speedBooting=false,speedBaseline=null,speedStory=null,speedFixedAccumulator=0,speedCountdownTimers=[],speedCategory='random',speedLastResult=null,speedSplitsOpen=false;

function speedHash(text){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}h^=h>>>16;h=Math.imul(h,2246822507);h^=h>>>13;h=Math.imul(h,3266489909);h^=h>>>16;return h>>>0;}
function speedHex(n){return('00000000'+(n>>>0).toString(16).toUpperCase()).slice(-8);}
function speedNormalizeSeed(value){const seed=String(value||'').toUpperCase().replace(/[^A-Z0-9-]+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'').slice(0,28);return seed||speedNewSeed();}
function speedNewSeed(){const values=new Uint32Array(2);if(globalThis.crypto?.getRandomValues)crypto.getRandomValues(values);else{values[0]=(speedNativeRandom()*0xffffffff)>>>0;values[1]=Date.now()>>>0;}return'EMBER-'+speedHex(values[0]).slice(0,4)+'-'+speedHex(values[1]).slice(0,4);}
function speedDailySeed(){return'DAILY-'+new Date().toISOString().slice(0,10).replaceAll('-','');}
function speedNext(holder,key='rngState'){let x=holder[key]>>>0;if(!x)x=0x6d2b79f5;x^=x<<13;x^=x>>>17;x^=x<<5;holder[key]=x>>>0;return(holder[key]>>>0)/4294967296;}
function speedWithRandom(holder,key,fn){const previous=Math.random;Math.random=()=>speedNext(holder,key);try{return fn();}finally{Math.random=previous;}}
function speedWithDerived(seed,label,fn){const holder={state:speedHash(seed+'|'+label)||1};return speedWithRandom(holder,'state',fn);}
function speedRun(){return G.run?.speedrun||((speedBooting||speedPending)&&speedPending)||null;}
function speedActive(){return !!speedRun();}
function speedCategoryName(category){return category==='seeded'?'ANY% FIXED SEED':'ANY% RANDOM SEED';}
function speedRta(sr=speedRun()){if(!sr?.startedAt)return 0;const end=sr.finishedAt||sr.stoppedAt||Date.now();return Math.max(0,Math.round(end-sr.startedAt));}
function speedIgt(){return Math.max(0,Math.round((G.run?.t||0)*1000));}
function speedTime(ms){ms=Math.max(0,Math.round(ms||0));const hours=Math.floor(ms/3600000),minutes=Math.floor(ms%3600000/60000),seconds=Math.floor(ms%60000/1000),millis=ms%1000;return(hours?hours+':'+String(minutes).padStart(2,'0'):String(minutes).padStart(2,'0'))+':'+String(seconds).padStart(2,'0')+'.'+String(millis).padStart(3,'0');}
function speedDelta(ms){if(!Number.isFinite(ms))return'—';return(ms<0?'−':'+')+speedTime(Math.abs(ms));}
function speedMakeStory(){const seen={};if(typeof HOLLOW_SCENES==='object')for(const id of Object.keys(HOLLOW_SCENES))if(!id.startsWith('wickPointer'))seen[id]=true;if(typeof TRACE_RECORDS==='object')for(const id of Object.keys(TRACE_RECORDS))seen[id]=true;return{seen,choices:{},archive:{version:1,echoes:{},skipped:{},guardians:{},guardianOrder:[],temper:{witness:0,shelter:0,defiance:0,severance:0},signals:[]}};}
function speedNeutralMeta(){return{dmg:1,hp:0,rate:1,speed:1,crit:0,mag:1,dash:1,xp:1,ess:1,revive:false,reload:1,charges:0,armor:0,floorHeal:0,regen:0,boss:1,flare:1,flareReach:0,flareCd:1,pierce:0,orbit:0,rarity:0,critPower:0,dashSpeed:1,dashIFrame:0,dashTrail:0,rekindleWard:0,overcharge:0,brand:0,boltNovaEvery:0,flareWave:false,critNova:false,steady:false};}
function speedRecordTemplate(){return{version:SPEEDRUN_VERSION,attempts:0,finishes:0,resets:0,best:{random:null,seeded:{}},history:[]};}
function speedCleanSplit(s){if(!s||!Number.isInteger(s.floor)||s.floor<1||s.floor>50||!Number.isFinite(s.rta)||s.rta<0||!Number.isFinite(s.igt)||s.igt<0)return null;return{floor:s.floor,rta:Math.round(Math.min(s.rta,1e12)),igt:Math.round(Math.min(s.igt,1e12)),name:String(s.name||'').slice(0,60)};}
function speedCleanResult(r){if(!r||typeof r!=='object'||!['random','seeded'].includes(r.category))return null;const seed=speedNormalizeSeed(r.seed),rta=Number(r.rta),igt=Number(r.igt);if(!Number.isFinite(rta)||rta<0||!Number.isFinite(igt)||igt<0)return null;return{category:r.category,seed,rta:Math.round(Math.min(rta,1e12)),igt:Math.round(Math.min(igt,1e12)),date:Math.max(0,Math.floor(Number(r.date)||0)),code:String(r.code||'').slice(0,40),kills:Math.max(0,Math.floor(Number(r.kills)||0)),level:Math.max(1,Math.floor(Number(r.level)||1)),guardianSplits:Array.isArray(r.guardianSplits)?r.guardianSplits.map(speedCleanSplit).filter(Boolean).slice(0,10):[]};}
function speedCleanRecords(raw){const out=speedRecordTemplate();if(!raw||typeof raw!=='object')return out;for(const key of ['attempts','finishes','resets'])out[key]=Math.max(0,Math.min(1e9,Math.floor(Number(raw[key])||0)));out.best.random=speedCleanResult(raw.best?.random);if(raw.best?.seeded&&typeof raw.best.seeded==='object'&&!Array.isArray(raw.best.seeded))for(const [seed,value]of Object.entries(raw.best.seeded).slice(-40)){const clean=speedCleanResult(value);if(clean)out.best.seeded[speedNormalizeSeed(seed)]=clean;}if(Array.isArray(raw.history))out.history=raw.history.map(r=>{const clean=speedCleanResult(r);if(!clean)return null;clean.status=r.status==='complete'?'complete':'dnf';clean.floor=Math.max(1,Math.min(50,Math.floor(Number(r.floor)||1)));return clean;}).filter(Boolean).slice(0,30);return out;}
function speedRecords(){if(!save.speedrunRecords||save.speedrunRecords.version!==SPEEDRUN_VERSION)save.speedrunRecords=speedCleanRecords(save.speedrunRecords);return save.speedrunRecords;}
function speedBest(category=speedCategory,seed=T('speedrunSeed')?.value){const records=speedRecords();return category==='seeded'?records.best.seeded[speedNormalizeSeed(seed)]||null:records.best.random||null;}
function speedRestoreProgress(){if(!speedBaseline)return;const kept={};for(const key of SPEEDRUN_KEEP)if(Object.prototype.hasOwnProperty.call(save,key))kept[key]=deepCopy(save[key]);for(const key of Object.keys(save))delete save[key];Object.assign(save,deepCopy(speedBaseline));for(const [key,value]of Object.entries(kept))save[key]=value;}
function speedCopy(text,button){const done=()=>{if(button){const label=button.textContent;button.textContent='COPIED';setTimeout(()=>button.textContent=label,1000);}};if(navigator.clipboard?.writeText){navigator.clipboard.writeText(text).then(done).catch(()=>speedCopyFallback(text,done));}else speedCopyFallback(text,done);}
function speedCopyFallback(text,done){const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();try{document.execCommand('copy');done();}catch(_){ }area.remove();}
function speedRunCode(result){return'TSE-'+speedHex(speedHash([result.category,result.seed,result.rta,result.igt,result.kills,result.level,result.guardianSplits.map(s=>s.rta).join('.')].join('|')));}
function speedReferenceSplit(pb,floor){return pb?.guardianSplits?.find(s=>s.floor===floor)||null;}

function speedRenderSetup(){const seed=T('speedrunSeed');if(!seed.value)seed.value=speedNewSeed();seed.value=speedNormalizeSeed(seed.value);seed.readOnly=speedCategory==='random';for(const button of document.querySelectorAll('[data-speedrun-category]')){const selected=button.dataset.speedrunCategory===speedCategory;button.classList.toggle('selected',selected);button.setAttribute('aria-selected',String(selected));}const records=speedRecords(),pb=speedBest();T('speedrunSetupPB').textContent=pb?speedTime(pb.rta):'NO FINISH';T('speedrunSetupAttempts').textContent=records.attempts;T('speedrunSetupFinishes').textContent=records.finishes;T('speedrunSetupResets').textContent=records.resets;const last=records.history[0];T('speedrunSetupLast').textContent=last?(last.status==='complete'?speedTime(last.rta):'DNF · F'+last.floor):'—';T('speedrunSeedHelp').textContent=speedCategory==='random'?'A fresh deterministic seed. Finishes compete with your overall Random Seed best.':'Repeat or share this exact dungeon. Records are stored separately for each seed.';const history=T('speedrunHistory');history.innerHTML=records.history.length?records.history.slice(0,6).map(r=>`<div class="speedrun-history-row"><b>${r.status==='complete'?'FINISH':'DNF · F'+r.floor}</b><span>${r.category==='seeded'?'FIXED · ':'RANDOM · '}${r.seed}</span><em>${speedTime(r.rta)}</em></div>`).join(''):'<div class="speedrun-history-empty">Completed runs and defeats will appear here.</div>';}
function speedOpenSetup(){if(speedCategory==='random')T('speedrunSeed').value=speedNewSeed();speedRenderSetup();show('speedrunSetup');T('speedrunStart').focus({preventScroll:true});}
function speedCloseSetup(){hide('speedrunSetup');T('btnSpeedrun')?.focus({preventScroll:true});}
function speedSetCategory(category){speedCategory=category==='seeded'?'seeded':'random';if(speedCategory==='random')T('speedrunSeed').value=speedNewSeed();speedRenderSetup();}

function speedCreateRun(category,seed){return{version:SPEEDRUN_VERSION,category,seed,seedHash:speedHex(speedHash(seed)),startedAt:0,finishedAt:0,stoppedAt:0,rngState:speedHash(seed+'|gameplay')||1,offerIndex:0,floorSplits:[],guardianSplits:[],armory:{},finished:false,ended:false,recorded:false,valid:true};}
function speedClearCountdown(){for(const id of speedCountdownTimers)clearTimeout(id);speedCountdownTimers=[];T('speedrunCountdown').hidden=true;}
function speedBeginCountdown(){const overlay=T('speedrunCountdown'),label=T('speedrunCountdownLabel'),sr=speedRun();speedClearCountdown();overlay.hidden=false;setState('speed-countdown');clearInput();const beats=['3','2','1','GO'];beats.forEach((beat,index)=>{const id=setTimeout(()=>{label.textContent=beat;label.className=beat==='GO'?'go':'';void label.offsetWidth;if(index===3){sr.startedAt=Date.now();sr.stoppedAt=0;G.run.t=0;speedFixedAccumulator=0;setState('playing');G.player.hitCd=Math.max(G.player.hitCd,1);save.resume=null;saveNow('speedrun-start');speedUpdateUi();G.cv.focus({preventScroll:true});speedCountdownTimers.push(setTimeout(()=>overlay.hidden=true,420));}},index*650);speedCountdownTimers.push(id);});}
function speedPrepareStart(config){const records=speedRecords();records.attempts++;save.resume=null;markSave();speedBaseline=deepCopy(save);speedStory=speedMakeStory();speedPending=speedCreateRun(config.category,speedNormalizeSeed(config.seed));speedBooting=true;const temporary={nodes:save.nodes,forms:save.forms,loadout:save.loadout,armory:save.armory,story:save.story,onboarding:save.onboarding};save.nodes={};save.forms={emberBolt:true,crownFlare:true,cinderstep:true};save.loadout={...SPEEDRUN_DEFAULT_FORMS};save.armory={};save.story=speedStory;save.onboarding={version:1,complete:true,seen:{}};try{speedStartRunBase();}finally{for(const [key,value]of Object.entries(temporary)){if(value===undefined)delete save[key];else save[key]=value;}speedBooting=false;}speedRestoreProgress();const sr=G.run?.speedrun;if(!sr){speedPending=null;speedBaseline=null;throw Error('The speedrun could not be started.');}speedPending=null;META=speedNeutralMeta();recalc();G.player.hp=G.player.maxHp;G.player.ammo=G.player.magSize;speedStory=speedMakeStory();for(const id of ['conversation','chapterClear','finale','speedrunSetup','speedrunResult']){if(id==='conversation')T(id).hidden=true;else hide(id);}document.body.classList.remove('conversing','remembering');document.body.classList.add('speedrun-active');speedSyncRunUi();speedRenderSplits();speedBeginCountdown();}
function speedRequestStart(){initAudio();sfx('ui');const config={category:speedCategory,seed:speedNormalizeSeed(T('speedrunSeed').value)};T('speedrunSeed').value=config.seed;const start=()=>speedPrepareStart(config);if(save.resume)confirmAction('REPLACE THE SAVED RUN?','The current descent will be replaced. Permanent progress is safe, and Speedrun Mode uses its own records.','BEGIN SPEEDRUN',start);else start();}
function speedRecordReset(){const sr=speedRun();if(!sr||sr.finished||sr.ended)return;sr.stoppedAt=Date.now();sr.ended=true;speedRecords().resets++;markSave();}
function speedRestart(){const sr=speedRun(),result=speedLastResult?.result;if(!sr&&!result)return;const config={category:sr?.category||result.category,seed:sr?.seed||result.seed};if(sr&&!sr.finished&&!sr.ended)speedRecordReset();speedRestoreProgress();save.resume=null;hide('pause');hide('dead');hide('speedrunResult');speedClearCountdown();speedPrepareStart(config);}

function speedRecordFloor(floor){const sr=speedRun();if(!sr?.startedAt||sr.finished||sr.floorSplits.some(s=>s.floor===floor))return;sr.floorSplits.push({floor,rta:speedRta(sr),igt:speedIgt(),name:floorName(floor)});}
function speedRecordGuardian(floor){const sr=speedRun();if(!sr?.startedAt||sr.finished||sr.guardianSplits.some(s=>s.floor===floor))return;const guardian=SPEEDRUN_GUARDIANS.find(g=>g.floor===floor);sr.guardianSplits.push({floor,rta:speedRta(sr),igt:speedIgt(),name:guardian?.name||'GUARDIAN'});speedRenderSplits();speedUpdateUi();saveNow('speedrun-split');}
function speedHistoryEntry(result,status,floor){return{...result,status,floor,guardianSplits:result.guardianSplits.map(s=>({...s}))};}
function speedRecordDnf(){const sr=speedRun();if(!sr||sr.recorded||sr.finished)return;sr.stoppedAt=Date.now();sr.ended=true;sr.recorded=true;const result={category:sr.category,seed:sr.seed,rta:speedRta(sr),igt:speedIgt(),date:Date.now(),code:'',kills:G.run?.kills||0,level:G.run?.level||1,guardianSplits:sr.guardianSplits.map(s=>({...s}))};result.code=speedRunCode(result);const records=speedRecords();records.history.unshift(speedHistoryEntry(result,'dnf',G.floor));records.history=records.history.slice(0,30);save.resume=null;markSave();T('speedrunDeathNote').textContent='RUN ENDED · RTA '+speedTime(result.rta)+' · FLOOR '+G.floor;speedRestoreProgress();saveNow('speedrun-dnf');}
function speedFinish(){const sr=speedRun();if(!sr||sr.finished)return;speedRecordGuardian(50);speedRecordFloor(50);sr.finishedAt=Date.now();sr.finished=true;sr.ended=true;const previous=speedBest(sr.category,sr.seed),result={category:sr.category,seed:sr.seed,rta:speedRta(sr),igt:speedIgt(),date:Date.now(),code:'',kills:G.run.kills,level:G.run.level,guardianSplits:sr.guardianSplits.map(s=>({...s}))};result.code=speedRunCode(result);const records=speedRecords(),isPB=sr.valid&&(!previous||result.rta<previous.rta);records.finishes++;if(isPB){if(sr.category==='random')records.best.random=deepCopy(result);else{records.best.seeded[sr.seed]=deepCopy(result);const seeds=Object.keys(records.best.seeded);if(seeds.length>40)delete records.best.seeded[seeds[0]];}}records.history.unshift(speedHistoryEntry(result,'complete',50));records.history=records.history.slice(0,30);sr.recorded=true;speedLastResult={result,previous,isPB};speedRestoreProgress();save.resume=null;markSave();clearInput();G.ebul=[];G.bullets=[];G.bossActive=false;hide('finale');hide('chapterClear');hide('pause');T('speedrunHud').hidden=true;T('speedrunSplits').hidden=true;setState('speed-finished');speedRenderResult(result,previous,isPB);show('speedrunResult');saveNow('speedrun-finish');sfx('victory');T('speedrunResultRetry').focus({preventScroll:true});}
function speedRenderResult(result,previous,isPB){T('speedrunResultKicker').textContent=speedCategoryName(result.category)+' · COMPLETE';T('speedrunResultRta').textContent=speedTime(result.rta);T('speedrunResultPB').textContent=isPB?(previous?'NEW PERSONAL BEST · '+speedDelta(result.rta-previous.rta):'FIRST FINISH · PERSONAL BEST'):previous?'FINISHED · '+speedDelta(result.rta-previous.rta)+' FROM BEST':'FINISHED · NO PERSONAL BEST';T('speedrunResultPB').classList.toggle('no-pb',!isPB);T('speedrunResultStats').innerHTML=`<span><b>${speedTime(result.igt)}</b>GAME TIME</span><span><b>${result.kills}</b>DEFEATED</span><span><b>LV ${result.level}</b>FINAL LEVEL</span><span><b>${result.seed}</b>SEED</span>`;T('speedrunResultSplits').innerHTML=SPEEDRUN_GUARDIANS.map(g=>{const split=result.guardianSplits.find(s=>s.floor===g.floor),old=speedReferenceSplit(previous,g.floor),delta=split&&old?split.rta-old.rta:NaN,cls=Number.isFinite(delta)?delta<=0?'ahead':'behind':'';return`<div><span>F${g.floor} · ${g.name}</span><b>${split?speedTime(split.rta):'—'}</b><em class="${cls}">${old&&split?speedDelta(delta):'NO COMPARISON'}</em></div>`;}).join('');T('speedrunResultCode').textContent=result.code;}
function speedResultsText(result=speedLastResult?.result){if(!result)return'';const previous=speedLastResult?.previous,lines=['THE SEVENTH EMBER — '+speedCategoryName(result.category),'Seed: '+result.seed,'RTA: '+speedTime(result.rta),'IGT: '+speedTime(result.igt),'Final level: '+result.level,'Enemies defeated: '+result.kills,'','Guardian splits:'];for(const g of SPEEDRUN_GUARDIANS){const s=result.guardianSplits.find(q=>q.floor===g.floor),old=speedReferenceSplit(previous,g.floor);lines.push('F'+g.floor+' '+g.name+': '+(s?speedTime(s.rta):'—')+(s&&old?' ('+speedDelta(s.rta-old.rta)+')':''));}lines.push('','Run code: '+result.code,'Ruleset: Standard v'+SPEEDRUN_VERSION);return lines.join('\n');}

function speedPace(){const sr=speedRun(),pb=sr&&speedBest(sr.category,sr.seed);if(!sr||!pb)return null;const last=sr.guardianSplits.at(-1);if(!last)return null;const old=speedReferenceSplit(pb,last.floor);return old?last.rta-old.rta:null;}
function speedRenderSplits(){const sr=speedRun();if(!sr)return;const pb=speedBest(sr.category,sr.seed),list=T('speedrunSplitList');list.innerHTML=SPEEDRUN_GUARDIANS.map((g,index)=>{const split=sr.guardianSplits.find(s=>s.floor===g.floor),old=speedReferenceSplit(pb,g.floor),delta=split&&old?split.rta-old.rta:NaN,done=!!split,current=!split&&(index===0||sr.guardianSplits.length===index),cls=done?'done':current?'current':'',deltaClass=Number.isFinite(delta)?delta<=0?'ahead':'behind':'';return`<div class="speedrun-split ${cls}"><i>${index+1}</i><span>${g.name}</span><b>${split?speedTime(split.rta):'—'}</b><em class="${deltaClass}">${split&&old?speedDelta(delta):''}</em></div>`;}).join('');T('speedrunSplitCategory').textContent=speedCategoryName(sr.category);T('speedrunSplitSeed').textContent=sr.seed;}
function speedUpdateUi(){const sr=speedRun(),hud=T('speedrunHud');if(!sr||sr.finished){hud.hidden=true;return;}hud.hidden=false;T('speedrunHudCategory').textContent=speedCategoryName(sr.category);T('speedrunRta').textContent=speedTime(speedRta(sr));T('speedrunIgt').textContent=speedTime(speedIgt());T('speedrunHudSeed').textContent=sr.seed+' · '+sr.seedHash;const pace=speedPace(),delta=T('speedrunDelta');delta.textContent=pace===null?'NO PACE':speedDelta(pace);delta.className=pace===null?'':pace<=0?'ahead':'behind';const running=G.state==='playing'||G.state==='speed-countdown',dead=G.dead||G.state==='dying'||G.state==='dead';T('btnSpeedRestartPause').hidden=!speedActive();T('speedrunPauseNote').hidden=!speedActive();T('btnSpeedRestartDead').hidden=!dead;T('speedrunDeathNote').hidden=!dead;T('btnDeadTree').hidden=dead;T('btnPauseMemories').hidden=speedActive();if(running&&speedSplitsOpen)T('speedrunSplits').hidden=false;}
function speedSyncRunUi(){const active=speedActive();document.body.classList.toggle('speedrun-active',active);T('btnSpeedRestartPause').hidden=!active;T('speedrunPauseNote').hidden=!active;T('btnPauseMemories').hidden=active;if(!active){T('speedrunHud').hidden=true;T('speedrunSplits').hidden=true;T('btnSpeedRestartDead').hidden=true;T('speedrunDeathNote').hidden=true;T('btnDeadTree').hidden=false;}}
function speedToggleSplits(force){if(!speedActive())return;speedSplitsOpen=typeof force==='boolean'?force:!speedSplitsOpen;speedRenderSplits();T('speedrunSplits').hidden=!speedSplitsOpen;}

const speedValidateSaveBase=validateSave;
validateSave=function(raw){const clean=speedValidateSaveBase(raw);clean.speedrunRecords=speedCleanRecords(raw?.speedrunRecords);return clean;};
const speedValidateCheckpointBase=validateCheckpoint;
validateCheckpoint=function(r){const out=speedValidateCheckpointBase(r),sr=r?.run?.speedrun;if(!sr)return out;const fail=()=>{throw Error('Invalid speedrun data');};if(sr.version!==SPEEDRUN_VERSION||!['random','seeded'].includes(sr.category)||typeof sr.seed!=='string'||sr.seed!==speedNormalizeSeed(sr.seed)||sr.seed.length>28||!Number.isInteger(sr.rngState)||sr.rngState<0||sr.rngState>0xffffffff||!Number.isInteger(sr.offerIndex)||sr.offerIndex<0||sr.offerIndex>10000)fail();for(const key of ['startedAt','finishedAt','stoppedAt'])if(!Number.isFinite(sr[key])||sr[key]<0||sr[key]>1e16)fail();for(const key of ['floorSplits','guardianSplits'])if(!Array.isArray(sr[key])||sr[key].length>50||sr[key].some(s=>!speedCleanSplit(s)))fail();if(!sr.armory||typeof sr.armory!=='object'||Array.isArray(sr.armory))fail();return out;};

const speedSaveNowBase=saveNow;
saveNow=function(reason='auto'){if(speedBooting)return true;if(speedActive())speedRestoreProgress();return speedSaveNowBase(reason);};
const speedComputeMetaBase=computeMeta;
computeMeta=function(){return speedRun()?speedNeutralMeta():speedComputeMetaBase();};
const speedArmoryDataBase=armoryData;
armoryData=function(){const sr=speedRun();if(sr){if(!sr.armory||typeof sr.armory!=='object')sr.armory={};return sr.armory;}return speedArmoryDataBase();};
const speedStoryDataBase=storyData;
storyData=function(){if(speedActive()){if(!speedStory)speedStory=speedMakeStory();return speedStory;}return speedStoryDataBase();};
const speedAdaptiveMasteryBase=adaptiveMastery;
adaptiveMastery=function(nodes){if(speedActive()){const tier=Math.max(1,Math.min(10,Math.ceil(Math.max(5,G.floor||5)/5)));return ADAPTIVE_REQUIREMENT[tier-1]||0;}return speedAdaptiveMasteryBase(nodes);};
const speedAddEssBase=addEss;
addEss=function(value){if(!speedActive())return speedAddEssBase(value);const amount=Math.round(value*(META.ess||1));if(amount>0&&G.run)G.run.ess+=amount;};
const speedBeginDialogueBase=beginDialogue;
beginDialogue=function(...args){if(speedActive())return false;return speedBeginDialogueBase(...args);};
const speedTickOnboardingBase=tickOnboarding;
tickOnboarding=function(dt){if(speedActive()){hideOnboardingCoach();return;}return speedTickOnboardingBase(dt);};
const speedShowChapterBase=showChapterClear;
showChapterClear=function(){if(!speedActive())return speedShowChapterBase();if(G.floor===5)G.run.hollowClearShown=true;if(G.floor===10)G.run.gardenClearShown=true;G.run.lateClearShown=G.floor;if(G.world?.lateCleared&&G.portal)G.portal.active=true;return false;};
const speedOpenTraceBase=openTrace;
openTrace=function(...args){if(speedActive())return false;return speedOpenTraceBase(...args);};
const speedRememberTraceBase=startRememberedTrace;
startRememberedTrace=function(...args){if(speedActive())return false;return speedRememberTraceBase(...args);};
const speedSetupFloorBase=setupFloor;
setupFloor=function(floor){const sr=G.run?.speedrun||speedPending;if(!sr)return speedSetupFloorBase(floor);if(G.run&&!G.run.speedrun)G.run.speedrun=sr;const out=speedWithDerived(sr.seed,'floor-'+floor,()=>speedSetupFloorBase(floor));sr.currentFloor=floor;return out;};
const speedBuildCardsBase=buildCards;
buildCards=function(){const sr=speedRun();if(!sr)return speedBuildCardsBase();const restored=Array.isArray(G.restoreCardIds)&&G.restoreCardIds.length>0,index=sr.offerIndex||0;if(!restored)sr.offerIndex=index+1;return speedWithDerived(sr.seed,'blessing-'+index,()=>speedBuildCardsBase());};
const speedUpdateBase=update;
update=function(dt){const sr=speedRun();if(!sr||!sr.startedAt||sr.finished)return speedUpdateBase(dt);speedFixedAccumulator=Math.min(.12,speedFixedAccumulator+Math.max(0,dt));let steps=0,result;while(speedFixedAccumulator+1e-9>=SPEEDRUN_STEP&&steps<7&&G.state==='playing'){result=speedWithRandom(sr,'rngState',()=>speedUpdateBase(SPEEDRUN_STEP));speedFixedAccumulator-=SPEEDRUN_STEP;steps++;}speedUpdateUi();return result;};
const speedSfxBase=sfx;
sfx=function(...args){if(!speedActive())return speedSfxBase(...args);const previous=Math.random;Math.random=speedNativeRandom;try{return speedSfxBase(...args);}finally{Math.random=previous;}};
const speedBurstBase=burst;
burst=function(...args){if(!speedActive())return speedBurstBase(...args);const previous=Math.random;Math.random=speedNativeRandom;try{return speedBurstBase(...args);}finally{Math.random=previous;}};
const speedDescendBase=descend;
descend=function(){if(speedActive()&&!G.descending&&G.state==='playing'&&G.portal?.active)speedRecordFloor(G.floor);return speedDescendBase();};
const speedKillBossBase=killBoss;
killBoss=function(b){const floor=G.floor,wasSpeed=speedActive(),out=speedKillBossBase(b);if(wasSpeed&&floor%5===0&&(G.portal?.active||b?.bossKey==='keeper'))speedRecordGuardian(floor);return out;};
const speedBeginEndingBase=beginEnding;
beginEnding=function(){if(speedActive()){speedFinish();return;}return speedBeginEndingBase();};
const speedDieBase=die;
die=function(){const wasSpeed=speedActive(),wasDead=G.dead,out=speedDieBase();if(wasSpeed&&!wasDead){speedRecordDnf();speedSyncRunUi();speedUpdateUi();}return out;};
const speedAbandonBase=abandonRun;
abandonRun=function(){if(speedActive())speedRecordReset();speedRestoreProgress();return speedAbandonBase();};
const speedBackToMenuBase=backToMenu;
backToMenu=function(){const wasSpeed=speedActive();if(wasSpeed)speedRestoreProgress();const out=speedBackToMenuBase();speedClearCountdown();speedPending=null;speedBooting=false;speedBaseline=null;speedStory=null;speedFixedAccumulator=0;speedSplitsOpen=false;speedSyncRunUi();hide('speedrunResult');return out;};
const speedResumeRunBase=resumeRun;
resumeRun=function(){const candidate=save.resume?.run?.speedrun;if(candidate){speedBaseline=deepCopy(save);speedStory=speedMakeStory();speedFixedAccumulator=0;}const out=speedResumeRunBase();if(G.run?.speedrun){META=speedNeutralMeta();recalc();speedSyncRunUi();speedRenderSplits();speedUpdateUi();}return out;};
const speedAnyBlockingBase=anyBlockingOverlay;
anyBlockingOverlay=function(){return T('speedrunSetup').classList.contains('open')||T('speedrunResult').classList.contains('open')||speedAnyBlockingBase();};
const speedEscBase=onEscKey;
onEscKey=function(){if(T('speedrunSetup').classList.contains('open')){speedCloseSetup();return;}if(T('speedrunSplits')&&!T('speedrunSplits').hidden){speedToggleSplits(false);return;}if(T('speedrunResult').classList.contains('open')){speedRestoreProgress();save.resume=null;saveNow('speedrun-result-close');speedBackToMenuBase();speedBaseline=null;speedStory=null;speedSyncRunUi();hide('speedrunResult');return;}return speedEscBase();};
const speedStartRunBase=startRun;

on(T('btnSpeedrun'),'click',()=>{initAudio();sfx('ui');speedOpenSetup();});
on(T('speedrunSetupClose'),'click',speedCloseSetup);on(T('speedrunSetupBack'),'click',speedCloseSetup);on(T('speedrunStart'),'click',speedRequestStart);
for(const button of document.querySelectorAll('[data-speedrun-category]'))on(button,'click',()=>speedSetCategory(button.dataset.speedrunCategory));
on(T('speedrunNewSeed'),'click',()=>{T('speedrunSeed').value=speedNewSeed();speedRenderSetup();T('speedrunSeed').focus();});
on(T('speedrunDailySeed'),'click',()=>{T('speedrunSeed').value=speedDailySeed();speedSetCategory('seeded');});
on(T('speedrunCopySeed'),'click',()=>speedCopy(speedNormalizeSeed(T('speedrunSeed').value),T('speedrunCopySeed')));
on(T('speedrunSeed'),'input',()=>{T('speedrunSeed').value=String(T('speedrunSeed').value||'').toUpperCase().replace(/[^A-Z0-9-]+/g,'-').replace(/-+/g,'-').replace(/^-+/,'').slice(0,28);});on(T('speedrunSeed'),'change',speedRenderSetup);
on(T('speedrunHud'),'click',()=>speedToggleSplits());on(T('speedrunSplitsClose'),'click',()=>speedToggleSplits(false));
on(T('btnSpeedRestartPause'),'click',speedRestart);on(T('btnSpeedRestartDead'),'click',speedRestart);on(T('speedrunResultRetry'),'click',speedRestart);
on(T('speedrunResultCopy'),'click',()=>speedCopy(speedResultsText(),T('speedrunResultCopy')));
on(T('speedrunResultMenu'),'click',()=>{speedRestoreProgress();save.resume=null;saveNow('speedrun-result-menu');speedBackToMenuBase();speedBaseline=null;speedStory=null;speedSyncRunUi();hide('speedrunResult');});
T('btnDeadMenu').addEventListener('click',event=>{if(!speedActive())return;event.preventDefault();event.stopImmediatePropagation();speedRestoreProgress();save.resume=null;saveNow('speedrun-death-menu');backToMenu();},true);
addEventListener('keydown',event=>{if(['INPUT','SELECT','TEXTAREA'].includes(event.target.tagName))return;if(event.code==='KeyT'&&speedActive()){event.preventDefault();event.stopImmediatePropagation();if(!event.repeat)speedToggleSplits();return;}if(event.code==='Backspace'&&event.shiftKey&&speedActive()){event.preventDefault();event.stopImmediatePropagation();if(!event.repeat)speedRestart();}},true);
setInterval(()=>{if(speedActive())speedUpdateUi();},67);

globalThis.TheSeventhEmberSpeedrun={version:SPEEDRUN_VERSION,get active(){return speedActive();},get run(){const sr=speedRun();return sr?deepCopy(sr):null;},get records(){return deepCopy(speedRecords());},formatTime:speedTime,normalizeSeed:speedNormalizeSeed};
document.documentElement.dataset.speedrun='standard-v1';
