const LATE_REGIONS = [
  {
    stage: 3,
    from: 11,
    to: 15,
    key: 'reservoir',
    name: 'The Drowned Reservoir',
    boss: 'THE BELLKEEPER',
    bossKey: 'bellkeeper',
    color: '#62c6d9',
    pi: 1,
    floors: [
      ['The Spillway', 'Water keeps finding the stairs.'],
      ['The Pump Gallery', 'The old pistons still move when the bells ring.'],
      ['The Sunken Walk', 'Ripples cross the path against the current.'],
      ['The Sluice Chapel', 'Someone built an altar around the main valve.'],
      ['The Bell Cistern', 'The Keeper is moving under the water.'],
    ],
  },
  {
    stage: 4,
    from: 16,
    to: 20,
    key: 'foundry',
    name: 'The Ember Foundry',
    boss: 'THE EMBER COLOSSUS',
    bossKey: 'colossus',
    color: '#ff9a56',
    pi: 2,
    floors: [
      ['The Cold Forge', 'The furnaces are dark, but the rails are warm.'],
      ['The Slag Run', 'The floor cools in patches. Use them.'],
      ['The Hammer Line', 'Every third hammer falls early.'],
      ['The Mold Vault', 'The empty molds are shaped like people.'],
      ['The Furnace Crown', 'The Colossus has started the main fire.'],
    ],
  },
  {
    stage: 5,
    from: 21,
    to: 25,
    key: 'observatory',
    name: 'The Shattered Observatory',
    boss: 'THE GLASS ASTRONOMER',
    bossKey: 'astronomer',
    color: '#80d9ef',
    pi: 3,
    floors: [
      ['The Fallen Orrery', 'The ceiling is moving. The room is not.'],
      ['The Meridian Hall', 'Broken lenses still follow warm things.'],
      ['The Parallax Walk', 'Two routes occupy the same corridor.'],
      ['The Blind Planetarium', 'Watch the glass, not the stars.'],
      ['The Shattered Dome', 'The Astronomer has corrected for your arrival.'],
    ],
  },
  {
    stage: 6,
    from: 26,
    to: 30,
    key: 'archive',
    name: 'The Buried Archive',
    boss: 'THE PALE SCRIBE',
    bossKey: 'scribe',
    color: '#d8c6a1',
    pi: 0,
    floors: [
      ['The Intake Desk', 'Every returned book is stamped with tomorrow’s date.'],
      ['The Flooded Index', 'The cards have swollen into little walls.'],
      ['The Redaction Rooms', 'The missing words move when you look away.'],
      ['The Misfiled Wing', 'Nothing here belongs on this shelf.'],
      ['The Last Margin', 'The Scribe has run out of paper.'],
    ],
  },
  {
    stage: 7,
    from: 31,
    to: 35,
    key: 'court',
    name: 'The Silent Court',
    boss: 'THE TWIN REGENTS',
    bossKey: 'regents',
    color: '#e49aa9',
    pi: 2,
    floors: [
      ['The Servants’ Door', 'Someone has set the table again.'],
      ['The Empty Banquet', 'The place cards turn when you pass.'],
      ['The Gallery of Favors', 'The portraits watch whichever half of the hall you use.'],
      ['The Divided Throne', 'The carpet was cut in half and stitched back together.'],
      ['The Audience Chamber', 'Two voices are arguing behind the door.'],
    ],
  },
  {
    stage: 8,
    from: 36,
    to: 40,
    key: 'choir',
    name: 'The Choir Spire',
    boss: 'THE VOID SERAPH',
    bossKey: 'seraph',
    color: '#a9b9ff',
    pi: 3,
    floors: [
      ['The Low Refrain', 'The stone hums under your feet.'],
      ['The Bell Lung', 'Breathe between the notes.'],
      ['The Cantor Stairs', 'An eighth step appears whenever the tower sings high.'],
      ['The Broken Octave', 'One filed-down tuning fork keeps the upper door shut.'],
      ['The Open Belfry', 'Something above you has stopped singing.'],
    ],
  },
  {
    stage: 9,
    from: 41,
    to: 45,
    key: 'citadel',
    name: 'The Black Citadel',
    boss: 'THE OBSIDIAN TYRANT',
    bossKey: 'tyrant',
    color: '#ff966d',
    pi: 2,
    floors: [
      ['The Inward Wall', 'The arrow slits face the wrong way.'],
      ['The Chain Ward', 'Every lock is fastened from inside.'],
      ['The Powder Chapel', 'The fuses are fresh.'],
      ['The King’s Engine', 'The floor shudders once every twelve seconds.'],
      ['The Siege Hall', 'The throne is walking toward you.'],
    ],
  },
  {
    stage: 10,
    from: 46,
    to: 50,
    key: 'heart',
    name: 'The Heart of the Star',
    boss: 'THE FIRST KEEPER',
    bossKey: 'keeper',
    color: '#ffd174',
    pi: 0,
    floors: [
      ['The Borrowed Gate', 'Pieces of the first floor drift in the dark.'],
      ['The Garden Without Soil', 'Roots hang in the outlines of missing beds.'],
      ['The Unwritten Room', 'Blank brass labels cover doors with no handles.'],
      ['The Door With Two Knocks', 'Knock once, wait, then knock again.'],
      ['The Heart of the Star', 'Wick dims when the cradle comes into view.'],
    ],
  },
];
const lateRegion = (f) => {
  const n = f > 50 ? 11 + ((f - 51) % 40) : f;
  return LATE_REGIONS.find((r) => n >= r.from && n <= r.to) || null;
};
const roman = (n) => ['', 'Ⅰ', 'Ⅱ', 'Ⅲ', 'Ⅳ', 'Ⅴ', 'Ⅵ', 'Ⅶ', 'Ⅷ', 'Ⅸ', 'Ⅹ'][n] || String(n);

const BLESSINGS = [
  {
    id: 'dmg',
    r: 0,
    max: 8,
    w: 12,
    icon: 'sparkles',
    name: 'Bright Core',
    ds: '+18% damage to Ember Bolt and Flare',
  },
  {
    id: 'rate',
    r: 0,
    max: 6,
    w: 11,
    icon: 'zap',
    name: 'Rapid Conjuring',
    ds: '+15% Ember Bolt casting rate',
  },
  {
    id: 'hp',
    r: 0,
    max: 6,
    w: 11,
    icon: 'heart',
    name: 'Vital Ember',
    ds: '+25 max health and restore 25 health',
  },
  { id: 'speed', r: 0, max: 5, w: 9, icon: 'wind', name: 'Cinderstep', ds: '+10% movement speed' },
  { id: 'magnet', r: 0, max: 4, w: 7, icon: 'magnet', name: 'Far Reach', ds: '+35% pickup reach' },
  { id: 'xp', r: 0, max: 5, w: 8, icon: 'book-open', name: 'Quick Study', ds: '+15% run XP' },
  {
    id: 'regen',
    r: 0,
    max: 4,
    w: 6,
    icon: 'activity',
    name: 'Steady Flame',
    ds: 'Restore 0.6 health each second',
  },
  {
    id: 'magazine',
    r: 0,
    max: 3,
    w: 7,
    icon: 'orbit',
    name: 'Deep Wells',
    ds: '+2 Ember Bolt charges',
  },
  {
    id: 'quickload',
    r: 0,
    max: 3,
    w: 7,
    icon: 'refresh-ccw',
    name: 'Quickening',
    ds: 'Rekindle 18% faster',
  },
  { id: 'edge', r: 0, max: 4, w: 8, icon: 'flame', name: 'Broad Flare', ds: '+25% Flare damage' },
  {
    id: 'dash',
    r: 0,
    max: 4,
    w: 7,
    icon: 'feather',
    name: 'Phantom Step',
    ds: 'Dash recovers 15% faster',
  },
  {
    id: 'flareReach',
    r: 0,
    max: 3,
    w: 7,
    icon: 'target',
    name: 'Long Spark',
    ds: '+16 Flare reach and a wider arc',
  },

  {
    id: 'proj',
    r: 1,
    max: 3,
    w: 6,
    icon: 'copy',
    name: 'Split Sigil',
    ds: '+1 Ember Bolt per cast',
  },
  {
    id: 'pierce',
    r: 1,
    max: 3,
    w: 6,
    icon: 'target',
    name: 'Piercing Light',
    ds: 'Ember Bolts pierce one more target',
  },
  { id: 'crit', r: 1, max: 4, w: 6, icon: 'eye', name: 'Clear Sight', ds: '+8% critical chance' },
  {
    id: 'orbital',
    r: 1,
    max: 4,
    w: 5,
    icon: 'orbit',
    name: 'Orbiting Cinders',
    ds: '+1 cinder that scorches nearby enemies',
  },
  {
    id: 'burn',
    r: 1,
    max: 3,
    w: 6,
    icon: 'flame',
    name: 'Searing Brand',
    ds: 'Ember Bolts ignite enemies for 3 seconds',
  },
  {
    id: 'blast',
    r: 1,
    max: 3,
    w: 5,
    icon: 'sparkles',
    name: 'Flashover',
    ds: 'Critical bolts scorch enemies around the target',
  },
  {
    id: 'guard',
    r: 1,
    max: 3,
    w: 6,
    icon: 'activity',
    name: 'Kindled Guard',
    ds: 'Rekindling grants a brief ward',
  },
  {
    id: 'dashTrail',
    r: 1,
    max: 3,
    w: 5,
    icon: 'wind',
    name: 'Wakefire',
    ds: 'Dash leaves a damaging trail of embers',
  },
  {
    id: 'reserve',
    r: 1,
    max: 2,
    w: 5,
    icon: 'gem',
    name: 'Hidden Spark',
    ds: '+1 charge and begin each floor fully Rekindled',
  },
  {
    id: 'pruning',
    r: 1,
    max: 2,
    w: 4,
    icon: 'sparkles',
    name: 'Pruning Flare',
    ds: '+60% Flare damage to summoned growth',
    unlock: 'pruning',
  },
  {
    id: 'leech',
    r: 1,
    max: 3,
    w: 5,
    icon: 'heart',
    name: 'Warm Hands',
    ds: 'Every sixth kill restores 5 health',
  },
  {
    id: 'fullHeart',
    r: 1,
    max: 2,
    w: 4,
    icon: 'flame',
    name: 'High Flame',
    ds: '+22% damage while above 80% health',
  },

  {
    id: 'ric',
    r: 2,
    max: 2,
    w: 4,
    icon: 'refresh-ccw',
    name: 'Ricochet Rune',
    ds: 'Ember Bolts jump to another enemy',
  },
  {
    id: 'exec',
    r: 2,
    max: 3,
    w: 4,
    icon: 'axe',
    name: 'Mercy Stroke',
    ds: '+30% damage against enemies below 30% health',
  },
  {
    id: 'afterbloom',
    r: 2,
    max: 1,
    w: 3,
    icon: 'heart',
    name: 'Afterbloom',
    ds: 'Critical hits can restore 2 health',
    unlock: 'afterbloom',
  },
  {
    id: 'bladeEcho',
    r: 2,
    max: 1,
    w: 3,
    icon: 'wind',
    name: 'Warden’s Wake',
    ds: 'Flare releases a piercing light crescent',
    unlock: 'bladeEcho',
  },
  {
    id: 'glass',
    r: 2,
    max: 2,
    w: 3,
    icon: 'flame',
    name: 'Glass Heart',
    ds: '+40% damage, but −10% maximum health',
  },
  {
    id: 'chain',
    r: 2,
    max: 2,
    w: 4,
    icon: 'zap',
    name: 'Chainfire',
    ds: 'Every fourth Bolt forks to two targets; rank 2 adds a third',
  },
  {
    id: 'thorns',
    r: 2,
    max: 3,
    w: 3,
    icon: 'activity',
    name: 'Reprisal',
    ds: 'Taking damage scorches the attacker',
  },
  {
    id: 'runRevive',
    r: 2,
    max: 1,
    w: 2,
    icon: 'heart',
    name: 'Second Ember',
    ds: 'Refuse one fatal hit during this descent',
  },
  {
    id: 'overcharge',
    r: 2,
    max: 2,
    w: 3,
    icon: 'sparkles',
    name: 'Overcharge',
    ds: 'Finishing Rekindle releases a damaging pulse',
  },
  {
    id: 'stillness',
    r: 2,
    max: 2,
    w: 3,
    icon: 'eye',
    name: 'Held Breath',
    ds: 'Standing still steadily increases Bolt damage',
  },
  {
    id: 'aftershock',
    r: 2,
    max: 2,
    w: 3,
    icon: 'orbit',
    name: 'Cinderstorm',
    ds: 'Flare erupts again after a short delay',
  },
  {
    id: 'eliteBane',
    r: 2,
    max: 2,
    w: 3,
    icon: 'skull',
    name: 'Star Eater',
    ds: '+35% damage to elites and guardians',
  },

  {
    id: 'whiteStar',
    r: 3,
    max: 1,
    w: 1,
    icon: 'sparkles',
    name: 'White Star',
    ds: 'Every fourth cast detonates for 280% damage across a vast area',
  },
  {
    id: 'twinFlame',
    r: 3,
    max: 1,
    w: 1,
    icon: 'copy',
    name: 'Twin Flame',
    ds: 'Every cast erupts forward, backward, and to both sides',
  },
  {
    id: 'lastLight',
    r: 3,
    max: 1,
    w: 1,
    icon: 'heart',
    name: 'Last Light',
    ds: 'Deal up to +200% damage as health falls',
  },
  {
    id: 'ashCrown',
    r: 3,
    max: 1,
    w: 1,
    icon: 'orbit',
    name: 'Crown of Ash',
    ds: 'Gain five empowered cinders; their hits spread a fierce Searing Brand',
  },
];
RARITY.splice(
  0,
  RARITY.length,
  { n: 'COMMON', c: '#9db4d0' },
  { n: 'UNCOMMON', c: '#65d9b1' },
  { n: 'RARE', c: '#b98aff' },
  { n: 'MYTHIC', c: '#ffbf5c' }
);
POOL.splice(0, POOL.length, ...BLESSINGS);

const TRACE_RECORDS = {};
